CREATE TABLE IF NOT EXISTS worker_heartbeats (
    worker_id VARCHAR(128) PRIMARY KEY,
    status VARCHAR(32) NOT NULL DEFAULT 'idle',
    current_job VARCHAR(128) NOT NULL DEFAULT '',
    cpu_usage DOUBLE PRECISION NOT NULL DEFAULT 0,
    ram_usage_mb DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_heartbeat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
