// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/contracts.go -destination=internal/usecase/mocks_repo_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/evrone/go-clean-template/internal/entity"
	repo "github.com/evrone/go-clean-template/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockUserRepo) GetByUsername(ctx context.Context, username string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepoMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepo)(nil).GetByUsername), ctx, username)
}

// List mocks base method.
func (m *MockUserRepo) List(ctx context.Context, page, limit int) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepoMockRecorder) List(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepo)(nil).List), ctx, page, limit)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, user)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskRepo) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepoMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepo)(nil).Delete), ctx, userID, taskID)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, userID string, filter repo.TaskFilter) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, userID, filter)
}

// Store mocks base method.
func (m *MockTaskRepo) Store(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTaskRepoMockRecorder) Store(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRepo)(nil).Store), ctx, task)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, task)
}

// MockVideoRepo is a mock of VideoRepo interface.
type MockVideoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepoMockRecorder
	isgomock struct{}
}

// MockVideoRepoMockRecorder is the mock recorder for MockVideoRepo.
type MockVideoRepoMockRecorder struct {
	mock *MockVideoRepo
}

// NewMockVideoRepo creates a new mock instance.
func NewMockVideoRepo(ctrl *gomock.Controller) *MockVideoRepo {
	mock := &MockVideoRepo{ctrl: ctrl}
	mock.recorder = &MockVideoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepo) EXPECT() *MockVideoRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVideoRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockVideoRepo) GetByID(ctx context.Context, id string) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideoRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockVideoRepo) List(ctx context.Context, filter repo.VideoFilter) ([]entity.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVideoRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVideoRepo)(nil).List), ctx, filter)
}

// Store mocks base method.
func (m *MockVideoRepo) Store(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockVideoRepoMockRecorder) Store(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockVideoRepo)(nil).Store), ctx, video)
}

// Update mocks base method.
func (m *MockVideoRepo) Update(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVideoRepoMockRecorder) Update(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoRepo)(nil).Update), ctx, video)
}

// MockWatchHistoryRepo is a mock of WatchHistoryRepo interface.
type MockWatchHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWatchHistoryRepoMockRecorder
	isgomock struct{}
}

// MockWatchHistoryRepoMockRecorder is the mock recorder for MockWatchHistoryRepo.
type MockWatchHistoryRepoMockRecorder struct {
	mock *MockWatchHistoryRepo
}

// NewMockWatchHistoryRepo creates a new mock instance.
func NewMockWatchHistoryRepo(ctrl *gomock.Controller) *MockWatchHistoryRepo {
	mock := &MockWatchHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockWatchHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchHistoryRepo) EXPECT() *MockWatchHistoryRepoMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockWatchHistoryRepo) ListByUser(ctx context.Context, userID string, limit, offset int) ([]entity.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockWatchHistoryRepoMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockWatchHistoryRepo)(nil).ListByUser), ctx, userID, limit, offset)
}

// Upsert mocks base method.
func (m *MockWatchHistoryRepo) Upsert(ctx context.Context, userID, videoID string, watchSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, userID, videoID, watchSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockWatchHistoryRepoMockRecorder) Upsert(ctx, userID, videoID, watchSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockWatchHistoryRepo)(nil).Upsert), ctx, userID, videoID, watchSeconds)
}

// MockFollowRepo is a mock of FollowRepo interface.
type MockFollowRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepoMockRecorder
	isgomock struct{}
}

// MockFollowRepoMockRecorder is the mock recorder for MockFollowRepo.
type MockFollowRepoMockRecorder struct {
	mock *MockFollowRepo
}

// NewMockFollowRepo creates a new mock instance.
func NewMockFollowRepo(ctrl *gomock.Controller) *MockFollowRepo {
	mock := &MockFollowRepo{ctrl: ctrl}
	mock.recorder = &MockFollowRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepo) EXPECT() *MockFollowRepoMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockFollowRepo) CountFollowers(ctx context.Context, channelID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, channelID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockFollowRepoMockRecorder) CountFollowers(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockFollowRepo)(nil).CountFollowers), ctx, channelID)
}

// Follow mocks base method.
func (m *MockFollowRepo) Follow(ctx context.Context, followerID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowRepoMockRecorder) Follow(ctx, followerID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowRepo)(nil).Follow), ctx, followerID, channelID)
}

// IsFollowing mocks base method.
func (m *MockFollowRepo) IsFollowing(ctx context.Context, followerID, channelID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, followerID, channelID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowRepoMockRecorder) IsFollowing(ctx, followerID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowRepo)(nil).IsFollowing), ctx, followerID, channelID)
}

// ListFollowedChannels mocks base method.
func (m *MockFollowRepo) ListFollowedChannels(ctx context.Context, followerID string, page, limit int) ([]entity.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowedChannels", ctx, followerID, page, limit)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFollowedChannels indicates an expected call of ListFollowedChannels.
func (mr *MockFollowRepoMockRecorder) ListFollowedChannels(ctx, followerID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowedChannels", reflect.TypeOf((*MockFollowRepo)(nil).ListFollowedChannels), ctx, followerID, page, limit)
}

// ListFollowers mocks base method.
func (m *MockFollowRepo) ListFollowers(ctx context.Context, channelID string, limit int) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowers", ctx, channelID, limit)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowers indicates an expected call of ListFollowers.
func (mr *MockFollowRepoMockRecorder) ListFollowers(ctx, channelID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowers", reflect.TypeOf((*MockFollowRepo)(nil).ListFollowers), ctx, channelID, limit)
}

// Unfollow mocks base method.
func (m *MockFollowRepo) Unfollow(ctx context.Context, followerID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, followerID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFollowRepoMockRecorder) Unfollow(ctx, followerID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFollowRepo)(nil).Unfollow), ctx, followerID, channelID)
}

// MockLivestreamRepo is a mock of LivestreamRepo interface.
type MockLivestreamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLivestreamRepoMockRecorder
	isgomock struct{}
}

// MockLivestreamRepoMockRecorder is the mock recorder for MockLivestreamRepo.
type MockLivestreamRepoMockRecorder struct {
	mock *MockLivestreamRepo
}

// NewMockLivestreamRepo creates a new mock instance.
func NewMockLivestreamRepo(ctrl *gomock.Controller) *MockLivestreamRepo {
	mock := &MockLivestreamRepo{ctrl: ctrl}
	mock.recorder = &MockLivestreamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLivestreamRepo) EXPECT() *MockLivestreamRepoMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockLivestreamRepo) CountActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockLivestreamRepoMockRecorder) CountActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockLivestreamRepo)(nil).CountActive), ctx)
}

// GetByID mocks base method.
func (m *MockLivestreamRepo) GetByID(ctx context.Context, id string) (entity.Livestream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Livestream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLivestreamRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLivestreamRepo)(nil).GetByID), ctx, id)
}

// GetByStreamKey mocks base method.
func (m *MockLivestreamRepo) GetByStreamKey(ctx context.Context, streamKey string) (entity.Livestream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStreamKey", ctx, streamKey)
	ret0, _ := ret[0].(entity.Livestream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStreamKey indicates an expected call of GetByStreamKey.
func (mr *MockLivestreamRepoMockRecorder) GetByStreamKey(ctx, streamKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStreamKey", reflect.TypeOf((*MockLivestreamRepo)(nil).GetByStreamKey), ctx, streamKey)
}

// GetByUserID mocks base method.
func (m *MockLivestreamRepo) GetByUserID(ctx context.Context, userID string) (entity.Livestream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(entity.Livestream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockLivestreamRepoMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockLivestreamRepo)(nil).GetByUserID), ctx, userID)
}

// ListActive mocks base method.
func (m *MockLivestreamRepo) ListActive(ctx context.Context, category string, limit, offset int) ([]entity.Livestream, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, category, limit, offset)
	ret0, _ := ret[0].([]entity.Livestream)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActive indicates an expected call of ListActive.
func (mr *MockLivestreamRepoMockRecorder) ListActive(ctx, category, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockLivestreamRepo)(nil).ListActive), ctx, category, limit, offset)
}

// Store mocks base method.
func (m *MockLivestreamRepo) Store(ctx context.Context, ls *entity.Livestream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, ls)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockLivestreamRepoMockRecorder) Store(ctx, ls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockLivestreamRepo)(nil).Store), ctx, ls)
}

// SumActiveViewers mocks base method.
func (m *MockLivestreamRepo) SumActiveViewers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumActiveViewers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumActiveViewers indicates an expected call of SumActiveViewers.
func (mr *MockLivestreamRepoMockRecorder) SumActiveViewers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumActiveViewers", reflect.TypeOf((*MockLivestreamRepo)(nil).SumActiveViewers), ctx)
}

// Update mocks base method.
func (m *MockLivestreamRepo) Update(ctx context.Context, ls *entity.Livestream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ls)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLivestreamRepoMockRecorder) Update(ctx, ls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLivestreamRepo)(nil).Update), ctx, ls)
}

// MockSubtitleRepo is a mock of SubtitleRepo interface.
type MockSubtitleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubtitleRepoMockRecorder
	isgomock struct{}
}

// MockSubtitleRepoMockRecorder is the mock recorder for MockSubtitleRepo.
type MockSubtitleRepoMockRecorder struct {
	mock *MockSubtitleRepo
}

// NewMockSubtitleRepo creates a new mock instance.
func NewMockSubtitleRepo(ctrl *gomock.Controller) *MockSubtitleRepo {
	mock := &MockSubtitleRepo{ctrl: ctrl}
	mock.recorder = &MockSubtitleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubtitleRepo) EXPECT() *MockSubtitleRepoMockRecorder {
	return m.recorder
}

// GetByVideoID mocks base method.
func (m *MockSubtitleRepo) GetByVideoID(ctx context.Context, videoID string) ([]entity.SubtitleCue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVideoID", ctx, videoID)
	ret0, _ := ret[0].([]entity.SubtitleCue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVideoID indicates an expected call of GetByVideoID.
func (mr *MockSubtitleRepoMockRecorder) GetByVideoID(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVideoID", reflect.TypeOf((*MockSubtitleRepo)(nil).GetByVideoID), ctx, videoID)
}

// ReplaceCues mocks base method.
func (m *MockSubtitleRepo) ReplaceCues(ctx context.Context, videoID string, cues []entity.SubtitleCue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCues", ctx, videoID, cues)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceCues indicates an expected call of ReplaceCues.
func (mr *MockSubtitleRepoMockRecorder) ReplaceCues(ctx, videoID, cues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCues", reflect.TypeOf((*MockSubtitleRepo)(nil).ReplaceCues), ctx, videoID, cues)
}

// MockWorkerRepo is a mock of WorkerRepo interface.
type MockWorkerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRepoMockRecorder
	isgomock struct{}
}

// MockWorkerRepoMockRecorder is the mock recorder for MockWorkerRepo.
type MockWorkerRepoMockRecorder struct {
	mock *MockWorkerRepo
}

// NewMockWorkerRepo creates a new mock instance.
func NewMockWorkerRepo(ctrl *gomock.Controller) *MockWorkerRepo {
	mock := &MockWorkerRepo{ctrl: ctrl}
	mock.recorder = &MockWorkerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRepo) EXPECT() *MockWorkerRepoMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockWorkerRepo) ListActive(ctx context.Context, staleAfter time.Duration) ([]entity.WorkerHeartbeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, staleAfter)
	ret0, _ := ret[0].([]entity.WorkerHeartbeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockWorkerRepoMockRecorder) ListActive(ctx, staleAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockWorkerRepo)(nil).ListActive), ctx, staleAfter)
}

// UpsertHeartbeat mocks base method.
func (m *MockWorkerRepo) UpsertHeartbeat(ctx context.Context, hb entity.WorkerHeartbeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertHeartbeat", ctx, hb)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertHeartbeat indicates an expected call of UpsertHeartbeat.
func (mr *MockWorkerRepoMockRecorder) UpsertHeartbeat(ctx, hb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertHeartbeat", reflect.TypeOf((*MockWorkerRepo)(nil).UpsertHeartbeat), ctx, hb)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// CountUnread mocks base method.
func (m *MockNotificationRepo) CountUnread(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockNotificationRepoMockRecorder) CountUnread(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockNotificationRepo)(nil).CountUnread), ctx, userID)
}

// ListByUserID mocks base method.
func (m *MockNotificationRepo) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]entity.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockNotificationRepoMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockNotificationRepo)(nil).ListByUserID), ctx, userID, limit, offset)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationRepo) MarkAllAsRead(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAllAsRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAllAsRead), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockNotificationRepo) MarkAsRead(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAsRead(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAsRead), ctx, id, userID)
}

// Store mocks base method.
func (m *MockNotificationRepo) Store(ctx context.Context, notif *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, notif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockNotificationRepoMockRecorder) Store(ctx, notif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockNotificationRepo)(nil).Store), ctx, notif)
}

// MockVocabularyRepo is a mock of VocabularyRepo interface.
type MockVocabularyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyRepoMockRecorder
	isgomock struct{}
}

// MockVocabularyRepoMockRecorder is the mock recorder for MockVocabularyRepo.
type MockVocabularyRepoMockRecorder struct {
	mock *MockVocabularyRepo
}

// NewMockVocabularyRepo creates a new mock instance.
func NewMockVocabularyRepo(ctrl *gomock.Controller) *MockVocabularyRepo {
	mock := &MockVocabularyRepo{ctrl: ctrl}
	mock.recorder = &MockVocabularyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabularyRepo) EXPECT() *MockVocabularyRepoMockRecorder {
	return m.recorder
}

// DeleteWord mocks base method.
func (m *MockVocabularyRepo) DeleteWord(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWord", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWord indicates an expected call of DeleteWord.
func (mr *MockVocabularyRepoMockRecorder) DeleteWord(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWord", reflect.TypeOf((*MockVocabularyRepo)(nil).DeleteWord), ctx, id, userID)
}

// ListByUserID mocks base method.
func (m *MockVocabularyRepo) ListByUserID(ctx context.Context, userID string) ([]entity.Vocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Vocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockVocabularyRepoMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockVocabularyRepo)(nil).ListByUserID), ctx, userID)
}

// SaveWord mocks base method.
func (m *MockVocabularyRepo) SaveWord(ctx context.Context, item *entity.Vocabulary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWord", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWord indicates an expected call of SaveWord.
func (mr *MockVocabularyRepoMockRecorder) SaveWord(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWord", reflect.TypeOf((*MockVocabularyRepo)(nil).SaveWord), ctx, item)
}

// MockAdminStatsRepo is a mock of AdminStatsRepo interface.
type MockAdminStatsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStatsRepoMockRecorder
	isgomock struct{}
}

// MockAdminStatsRepoMockRecorder is the mock recorder for MockAdminStatsRepo.
type MockAdminStatsRepoMockRecorder struct {
	mock *MockAdminStatsRepo
}

// NewMockAdminStatsRepo creates a new mock instance.
func NewMockAdminStatsRepo(ctrl *gomock.Controller) *MockAdminStatsRepo {
	mock := &MockAdminStatsRepo{ctrl: ctrl}
	mock.recorder = &MockAdminStatsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStatsRepo) EXPECT() *MockAdminStatsRepoMockRecorder {
	return m.recorder
}

// CategoryBreakdown mocks base method.
func (m *MockAdminStatsRepo) CategoryBreakdown(ctx context.Context) ([]entity.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryBreakdown", ctx)
	ret0, _ := ret[0].([]entity.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategoryBreakdown indicates an expected call of CategoryBreakdown.
func (mr *MockAdminStatsRepoMockRecorder) CategoryBreakdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryBreakdown", reflect.TypeOf((*MockAdminStatsRepo)(nil).CategoryBreakdown), ctx)
}

// ChannelStats mocks base method.
func (m *MockAdminStatsRepo) ChannelStats(ctx context.Context) (entity.ChannelStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChannelStats", ctx)
	ret0, _ := ret[0].(entity.ChannelStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChannelStats indicates an expected call of ChannelStats.
func (mr *MockAdminStatsRepoMockRecorder) ChannelStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChannelStats", reflect.TypeOf((*MockAdminStatsRepo)(nil).ChannelStats), ctx)
}

// MockCommentRepo is a mock of CommentRepo interface.
type MockCommentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepoMockRecorder
	isgomock struct{}
}

// MockCommentRepoMockRecorder is the mock recorder for MockCommentRepo.
type MockCommentRepoMockRecorder struct {
	mock *MockCommentRepo
}

// NewMockCommentRepo creates a new mock instance.
func NewMockCommentRepo(ctrl *gomock.Controller) *MockCommentRepo {
	mock := &MockCommentRepo{ctrl: ctrl}
	mock.recorder = &MockCommentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepo) EXPECT() *MockCommentRepoMockRecorder {
	return m.recorder
}

// CountAllByVideoID mocks base method.
func (m *MockCommentRepo) CountAllByVideoID(ctx context.Context, videoID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAllByVideoID", ctx, videoID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAllByVideoID indicates an expected call of CountAllByVideoID.
func (mr *MockCommentRepoMockRecorder) CountAllByVideoID(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAllByVideoID", reflect.TypeOf((*MockCommentRepo)(nil).CountAllByVideoID), ctx, videoID)
}

// GetByID mocks base method.
func (m *MockCommentRepo) GetByID(ctx context.Context, id string) (entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentRepo)(nil).GetByID), ctx, id)
}

// ListByVideoID mocks base method.
func (m *MockCommentRepo) ListByVideoID(ctx context.Context, videoID string, limit, offset uint64) ([]entity.Comment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVideoID", ctx, videoID, limit, offset)
	ret0, _ := ret[0].([]entity.Comment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVideoID indicates an expected call of ListByVideoID.
func (mr *MockCommentRepoMockRecorder) ListByVideoID(ctx, videoID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVideoID", reflect.TypeOf((*MockCommentRepo)(nil).ListByVideoID), ctx, videoID, limit, offset)
}

// ListRepliesByParentID mocks base method.
func (m *MockCommentRepo) ListRepliesByParentID(ctx context.Context, parentID string, limit, offset uint64) ([]entity.Comment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepliesByParentID", ctx, parentID, limit, offset)
	ret0, _ := ret[0].([]entity.Comment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRepliesByParentID indicates an expected call of ListRepliesByParentID.
func (mr *MockCommentRepoMockRecorder) ListRepliesByParentID(ctx, parentID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepliesByParentID", reflect.TypeOf((*MockCommentRepo)(nil).ListRepliesByParentID), ctx, parentID, limit, offset)
}

// Store mocks base method.
func (m *MockCommentRepo) Store(ctx context.Context, c *entity.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCommentRepoMockRecorder) Store(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCommentRepo)(nil).Store), ctx, c)
}

// MockUserPreferenceRepo is a mock of UserPreferenceRepo interface.
type MockUserPreferenceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserPreferenceRepoMockRecorder
	isgomock struct{}
}

// MockUserPreferenceRepoMockRecorder is the mock recorder for MockUserPreferenceRepo.
type MockUserPreferenceRepoMockRecorder struct {
	mock *MockUserPreferenceRepo
}

// NewMockUserPreferenceRepo creates a new mock instance.
func NewMockUserPreferenceRepo(ctrl *gomock.Controller) *MockUserPreferenceRepo {
	mock := &MockUserPreferenceRepo{ctrl: ctrl}
	mock.recorder = &MockUserPreferenceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPreferenceRepo) EXPECT() *MockUserPreferenceRepoMockRecorder {
	return m.recorder
}

// GetCategories mocks base method.
func (m *MockUserPreferenceRepo) GetCategories(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockUserPreferenceRepoMockRecorder) GetCategories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockUserPreferenceRepo)(nil).GetCategories), ctx, userID)
}

// SetCategories mocks base method.
func (m *MockUserPreferenceRepo) SetCategories(ctx context.Context, userID string, categories []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCategories", ctx, userID, categories)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCategories indicates an expected call of SetCategories.
func (mr *MockUserPreferenceRepoMockRecorder) SetCategories(ctx, userID, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCategories", reflect.TypeOf((*MockUserPreferenceRepo)(nil).SetCategories), ctx, userID, categories)
}

// MockLikeRepo is a mock of LikeRepo interface.
type MockLikeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepoMockRecorder
	isgomock struct{}
}

// MockLikeRepoMockRecorder is the mock recorder for MockLikeRepo.
type MockLikeRepoMockRecorder struct {
	mock *MockLikeRepo
}

// NewMockLikeRepo creates a new mock instance.
func NewMockLikeRepo(ctrl *gomock.Controller) *MockLikeRepo {
	mock := &MockLikeRepo{ctrl: ctrl}
	mock.recorder = &MockLikeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepo) EXPECT() *MockLikeRepoMockRecorder {
	return m.recorder
}

// GetLikeCount mocks base method.
func (m *MockLikeRepo) GetLikeCount(ctx context.Context, videoID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCount", ctx, videoID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikeCount indicates an expected call of GetLikeCount.
func (mr *MockLikeRepoMockRecorder) GetLikeCount(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCount", reflect.TypeOf((*MockLikeRepo)(nil).GetLikeCount), ctx, videoID)
}

// IncrementHeart mocks base method.
func (m *MockLikeRepo) IncrementHeart(ctx context.Context, streamID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementHeart", ctx, streamID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementHeart indicates an expected call of IncrementHeart.
func (mr *MockLikeRepoMockRecorder) IncrementHeart(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementHeart", reflect.TypeOf((*MockLikeRepo)(nil).IncrementHeart), ctx, streamID)
}

// IsLikedByUser mocks base method.
func (m *MockLikeRepo) IsLikedByUser(ctx context.Context, videoID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLikedByUser", ctx, videoID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLikedByUser indicates an expected call of IsLikedByUser.
func (mr *MockLikeRepoMockRecorder) IsLikedByUser(ctx, videoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLikedByUser", reflect.TypeOf((*MockLikeRepo)(nil).IsLikedByUser), ctx, videoID, userID)
}

// ToggleLike mocks base method.
func (m *MockLikeRepo) ToggleLike(ctx context.Context, l *entity.VideoLike) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", ctx, l)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockLikeRepoMockRecorder) ToggleLike(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockLikeRepo)(nil).ToggleLike), ctx, l)
}

// MockSavedVideoRepo is a mock of SavedVideoRepo interface.
type MockSavedVideoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSavedVideoRepoMockRecorder
	isgomock struct{}
}

// MockSavedVideoRepoMockRecorder is the mock recorder for MockSavedVideoRepo.
type MockSavedVideoRepoMockRecorder struct {
	mock *MockSavedVideoRepo
}

// NewMockSavedVideoRepo creates a new mock instance.
func NewMockSavedVideoRepo(ctrl *gomock.Controller) *MockSavedVideoRepo {
	mock := &MockSavedVideoRepo{ctrl: ctrl}
	mock.recorder = &MockSavedVideoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavedVideoRepo) EXPECT() *MockSavedVideoRepoMockRecorder {
	return m.recorder
}

// IsSavedByUser mocks base method.
func (m *MockSavedVideoRepo) IsSavedByUser(ctx context.Context, videoID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSavedByUser", ctx, videoID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSavedByUser indicates an expected call of IsSavedByUser.
func (mr *MockSavedVideoRepoMockRecorder) IsSavedByUser(ctx, videoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSavedByUser", reflect.TypeOf((*MockSavedVideoRepo)(nil).IsSavedByUser), ctx, videoID, userID)
}

// ListSavedVideos mocks base method.
func (m *MockSavedVideoRepo) ListSavedVideos(ctx context.Context, userID string, limit, offset int) ([]entity.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavedVideos", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSavedVideos indicates an expected call of ListSavedVideos.
func (mr *MockSavedVideoRepoMockRecorder) ListSavedVideos(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavedVideos", reflect.TypeOf((*MockSavedVideoRepo)(nil).ListSavedVideos), ctx, userID, limit, offset)
}

// ToggleSave mocks base method.
func (m *MockSavedVideoRepo) ToggleSave(ctx context.Context, userID, videoID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleSave", ctx, userID, videoID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleSave indicates an expected call of ToggleSave.
func (mr *MockSavedVideoRepoMockRecorder) ToggleSave(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleSave", reflect.TypeOf((*MockSavedVideoRepo)(nil).ToggleSave), ctx, userID, videoID)
}

// MockCommentLikeRepo is a mock of CommentLikeRepo interface.
type MockCommentLikeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommentLikeRepoMockRecorder
	isgomock struct{}
}

// MockCommentLikeRepoMockRecorder is the mock recorder for MockCommentLikeRepo.
type MockCommentLikeRepoMockRecorder struct {
	mock *MockCommentLikeRepo
}

// NewMockCommentLikeRepo creates a new mock instance.
func NewMockCommentLikeRepo(ctrl *gomock.Controller) *MockCommentLikeRepo {
	mock := &MockCommentLikeRepo{ctrl: ctrl}
	mock.recorder = &MockCommentLikeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentLikeRepo) EXPECT() *MockCommentLikeRepoMockRecorder {
	return m.recorder
}

// GetLikeCount mocks base method.
func (m *MockCommentLikeRepo) GetLikeCount(ctx context.Context, commentID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCount", ctx, commentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikeCount indicates an expected call of GetLikeCount.
func (mr *MockCommentLikeRepoMockRecorder) GetLikeCount(ctx, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCount", reflect.TypeOf((*MockCommentLikeRepo)(nil).GetLikeCount), ctx, commentID)
}

// IsLikedByUser mocks base method.
func (m *MockCommentLikeRepo) IsLikedByUser(ctx context.Context, commentID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLikedByUser", ctx, commentID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLikedByUser indicates an expected call of IsLikedByUser.
func (mr *MockCommentLikeRepoMockRecorder) IsLikedByUser(ctx, commentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLikedByUser", reflect.TypeOf((*MockCommentLikeRepo)(nil).IsLikedByUser), ctx, commentID, userID)
}

// ToggleLike mocks base method.
func (m *MockCommentLikeRepo) ToggleLike(ctx context.Context, commentID, userID string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", ctx, commentID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockCommentLikeRepoMockRecorder) ToggleLike(ctx, commentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockCommentLikeRepo)(nil).ToggleLike), ctx, commentID, userID)
}
