// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	request "github.com/evrone/go-clean-template/internal/controller/restapi/v1/request"
	response "github.com/evrone/go-clean-template/internal/controller/restapi/v1/response"
	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
	isgomock struct{}
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(ctx context.Context, userID string) (entity.TranslationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, userID)
	ret0, _ := ret[0].(entity.TranslationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), ctx, userID)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(ctx context.Context, userID string, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, userID, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), ctx, userID, t)
}

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// RefreshToken mocks base method.
func (m *MockUser) RefreshToken(ctx context.Context, refreshToken string) (response.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(response.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockUserMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockUser)(nil).RefreshToken), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// UpdateUser mocks base method.
func (m *MockUser) UpdateUser(ctx context.Context, userID, username, email, avatar string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, username, email, avatar)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserMockRecorder) UpdateUser(ctx, userID, username, email, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUser)(nil).UpdateUser), ctx, userID, username, email, avatar)
}

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
	isgomock struct{}
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTask) Create(ctx context.Context, userID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskMockRecorder) Create(ctx, userID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTask)(nil).Create), ctx, userID, title, description)
}

// Delete mocks base method.
func (m *MockTask) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTask)(nil).Delete), ctx, userID, taskID)
}

// Get mocks base method.
func (m *MockTask) Get(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskMockRecorder) Get(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTask)(nil).Get), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTask) List(ctx context.Context, userID string, status *entity.TaskStatus, limit, offset int) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskMockRecorder) List(ctx, userID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTask)(nil).List), ctx, userID, status, limit, offset)
}

// Transition mocks base method.
func (m *MockTask) Transition(ctx context.Context, userID, taskID string, newStatus entity.TaskStatus) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, userID, taskID, newStatus)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transition indicates an expected call of Transition.
func (mr *MockTaskMockRecorder) Transition(ctx, userID, taskID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockTask)(nil).Transition), ctx, userID, taskID, newStatus)
}

// Update mocks base method.
func (m *MockTask) Update(ctx context.Context, userID, taskID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, taskID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskMockRecorder) Update(ctx, userID, taskID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTask)(nil).Update), ctx, userID, taskID, title, description)
}

// MockVideo is a mock of Video interface.
type MockVideo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoMockRecorder
	isgomock struct{}
}

// MockVideoMockRecorder is the mock recorder for MockVideo.
type MockVideoMockRecorder struct {
	mock *MockVideo
}

// NewMockVideo creates a new mock instance.
func NewMockVideo(ctrl *gomock.Controller) *MockVideo {
	mock := &MockVideo{ctrl: ctrl}
	mock.recorder = &MockVideoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideo) EXPECT() *MockVideoMockRecorder {
	return m.recorder
}

// ConfirmUpload mocks base method.
func (m *MockVideo) ConfirmUpload(ctx context.Context, userID string, req request.ConfirmUpload) (response.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmUpload", ctx, userID, req)
	ret0, _ := ret[0].(response.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmUpload indicates an expected call of ConfirmUpload.
func (mr *MockVideoMockRecorder) ConfirmUpload(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmUpload", reflect.TypeOf((*MockVideo)(nil).ConfirmUpload), ctx, userID, req)
}

// CreateUpload mocks base method.
func (m *MockVideo) CreateUpload(ctx context.Context, userID string, req request.CreateVideoUpload) (response.UploadUrlResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUpload", ctx, userID, req)
	ret0, _ := ret[0].(response.UploadUrlResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUpload indicates an expected call of CreateUpload.
func (mr *MockVideoMockRecorder) CreateUpload(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUpload", reflect.TypeOf((*MockVideo)(nil).CreateUpload), ctx, userID, req)
}

// DeleteVideo mocks base method.
func (m *MockVideo) DeleteVideo(ctx context.Context, userID, videoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoMockRecorder) DeleteVideo(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideo)(nil).DeleteVideo), ctx, userID, videoID)
}

// GetByID mocks base method.
func (m *MockVideo) GetByID(ctx context.Context, id string) (response.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(response.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideo)(nil).GetByID), ctx, id)
}

// HandleTranscodeCallback mocks base method.
func (m *MockVideo) HandleTranscodeCallback(ctx context.Context, videoID, status, hlsMasterURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTranscodeCallback", ctx, videoID, status, hlsMasterURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleTranscodeCallback indicates an expected call of HandleTranscodeCallback.
func (mr *MockVideoMockRecorder) HandleTranscodeCallback(ctx, videoID, status, hlsMasterURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTranscodeCallback", reflect.TypeOf((*MockVideo)(nil).HandleTranscodeCallback), ctx, videoID, status, hlsMasterURL)
}

// ListPublicVideos mocks base method.
func (m *MockVideo) ListPublicVideos(ctx context.Context, userID, category, query string, page, limit int) (response.PageResponse[response.VideoResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicVideos", ctx, userID, category, query, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.VideoResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicVideos indicates an expected call of ListPublicVideos.
func (mr *MockVideoMockRecorder) ListPublicVideos(ctx, userID, category, query, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicVideos", reflect.TypeOf((*MockVideo)(nil).ListPublicVideos), ctx, userID, category, query, page, limit)
}

// ListStudioVideos mocks base method.
func (m *MockVideo) ListStudioVideos(ctx context.Context, userID string, page, limit int) (response.PageResponse[response.VideoResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStudioVideos", ctx, userID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.VideoResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStudioVideos indicates an expected call of ListStudioVideos.
func (mr *MockVideoMockRecorder) ListStudioVideos(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStudioVideos", reflect.TypeOf((*MockVideo)(nil).ListStudioVideos), ctx, userID, page, limit)
}

// PublishVideo mocks base method.
func (m *MockVideo) PublishVideo(ctx context.Context, userID, videoID string) (response.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVideo", ctx, userID, videoID)
	ret0, _ := ret[0].(response.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishVideo indicates an expected call of PublishVideo.
func (mr *MockVideoMockRecorder) PublishVideo(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVideo", reflect.TypeOf((*MockVideo)(nil).PublishVideo), ctx, userID, videoID)
}

// RecordView mocks base method.
func (m *MockVideo) RecordView(ctx context.Context, videoID, clientIP, deviceID string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordView", ctx, videoID, clientIP, deviceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordView indicates an expected call of RecordView.
func (mr *MockVideoMockRecorder) RecordView(ctx, videoID, clientIP, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordView", reflect.TypeOf((*MockVideo)(nil).RecordView), ctx, videoID, clientIP, deviceID)
}

// UpdateThumbnail mocks base method.
func (m *MockVideo) UpdateThumbnail(ctx context.Context, userID, videoID string, req request.UpdateThumbnail) (response.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbnail", ctx, userID, videoID, req)
	ret0, _ := ret[0].(response.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateThumbnail indicates an expected call of UpdateThumbnail.
func (mr *MockVideoMockRecorder) UpdateThumbnail(ctx, userID, videoID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbnail", reflect.TypeOf((*MockVideo)(nil).UpdateThumbnail), ctx, userID, videoID, req)
}

// UpdateVideo mocks base method.
func (m *MockVideo) UpdateVideo(ctx context.Context, userID, videoID string, req request.UpdateVideo) (response.VideoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideo", ctx, userID, videoID, req)
	ret0, _ := ret[0].(response.VideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVideo indicates an expected call of UpdateVideo.
func (mr *MockVideoMockRecorder) UpdateVideo(ctx, userID, videoID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideo", reflect.TypeOf((*MockVideo)(nil).UpdateVideo), ctx, userID, videoID, req)
}

// MockLivestream is a mock of Livestream interface.
type MockLivestream struct {
	ctrl     *gomock.Controller
	recorder *MockLivestreamMockRecorder
	isgomock struct{}
}

// MockLivestreamMockRecorder is the mock recorder for MockLivestream.
type MockLivestreamMockRecorder struct {
	mock *MockLivestream
}

// NewMockLivestream creates a new mock instance.
func NewMockLivestream(ctrl *gomock.Controller) *MockLivestream {
	mock := &MockLivestream{ctrl: ctrl}
	mock.recorder = &MockLivestreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLivestream) EXPECT() *MockLivestreamMockRecorder {
	return m.recorder
}

// AuthenticateStreamKey mocks base method.
func (m *MockLivestream) AuthenticateStreamKey(ctx context.Context, req request.StreamKeyAuth) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateStreamKey", ctx, req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateStreamKey indicates an expected call of AuthenticateStreamKey.
func (mr *MockLivestreamMockRecorder) AuthenticateStreamKey(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateStreamKey", reflect.TypeOf((*MockLivestream)(nil).AuthenticateStreamKey), ctx, req)
}

// GetStreamByID mocks base method.
func (m *MockLivestream) GetStreamByID(ctx context.Context, id string) (response.LivestreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamByID", ctx, id)
	ret0, _ := ret[0].(response.LivestreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamByID indicates an expected call of GetStreamByID.
func (mr *MockLivestreamMockRecorder) GetStreamByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamByID", reflect.TypeOf((*MockLivestream)(nil).GetStreamByID), ctx, id)
}

// GetStreamKey mocks base method.
func (m *MockLivestream) GetStreamKey(ctx context.Context, userID string) (response.StreamKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamKey", ctx, userID)
	ret0, _ := ret[0].(response.StreamKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamKey indicates an expected call of GetStreamKey.
func (mr *MockLivestreamMockRecorder) GetStreamKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamKey", reflect.TypeOf((*MockLivestream)(nil).GetStreamKey), ctx, userID)
}

// HandleDVRComplete mocks base method.
func (m *MockLivestream) HandleDVRComplete(ctx context.Context, streamKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDVRComplete", ctx, streamKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDVRComplete indicates an expected call of HandleDVRComplete.
func (mr *MockLivestreamMockRecorder) HandleDVRComplete(ctx, streamKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDVRComplete", reflect.TypeOf((*MockLivestream)(nil).HandleDVRComplete), ctx, streamKey)
}

// ListActiveStreams mocks base method.
func (m *MockLivestream) ListActiveStreams(ctx context.Context, category string, page, limit int) (response.PageResponse[response.LivestreamResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveStreams", ctx, category, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.LivestreamResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveStreams indicates an expected call of ListActiveStreams.
func (mr *MockLivestreamMockRecorder) ListActiveStreams(ctx, category, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveStreams", reflect.TypeOf((*MockLivestream)(nil).ListActiveStreams), ctx, category, page, limit)
}

// ResetStreamKey mocks base method.
func (m *MockLivestream) ResetStreamKey(ctx context.Context, userID string) (response.StreamKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStreamKey", ctx, userID)
	ret0, _ := ret[0].(response.StreamKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetStreamKey indicates an expected call of ResetStreamKey.
func (mr *MockLivestreamMockRecorder) ResetStreamKey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStreamKey", reflect.TypeOf((*MockLivestream)(nil).ResetStreamKey), ctx, userID)
}

// SendChatMessage mocks base method.
func (m *MockLivestream) SendChatMessage(ctx context.Context, streamID string, req request.SendChatMessage) (response.ChatMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChatMessage", ctx, streamID, req)
	ret0, _ := ret[0].(response.ChatMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendChatMessage indicates an expected call of SendChatMessage.
func (mr *MockLivestreamMockRecorder) SendChatMessage(ctx, streamID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChatMessage", reflect.TypeOf((*MockLivestream)(nil).SendChatMessage), ctx, streamID, req)
}

// SubscribeChat mocks base method.
func (m *MockLivestream) SubscribeChat(streamID string) (<-chan response.ChatMessageResponse, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeChat", streamID)
	ret0, _ := ret[0].(<-chan response.ChatMessageResponse)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeChat indicates an expected call of SubscribeChat.
func (mr *MockLivestreamMockRecorder) SubscribeChat(streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeChat", reflect.TypeOf((*MockLivestream)(nil).SubscribeChat), streamID)
}

// UnpublishStream mocks base method.
func (m *MockLivestream) UnpublishStream(ctx context.Context, streamKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishStream", ctx, streamKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishStream indicates an expected call of UnpublishStream.
func (mr *MockLivestreamMockRecorder) UnpublishStream(ctx, streamKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishStream", reflect.TypeOf((*MockLivestream)(nil).UnpublishStream), ctx, streamKey)
}

// UpdateStreamInfo mocks base method.
func (m *MockLivestream) UpdateStreamInfo(ctx context.Context, userID string, req request.UpdateLivestreamInfo) (response.LivestreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamInfo", ctx, userID, req)
	ret0, _ := ret[0].(response.LivestreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamInfo indicates an expected call of UpdateStreamInfo.
func (mr *MockLivestreamMockRecorder) UpdateStreamInfo(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamInfo", reflect.TypeOf((*MockLivestream)(nil).UpdateStreamInfo), ctx, userID, req)
}

// MockSubtitle is a mock of Subtitle interface.
type MockSubtitle struct {
	ctrl     *gomock.Controller
	recorder *MockSubtitleMockRecorder
	isgomock struct{}
}

// MockSubtitleMockRecorder is the mock recorder for MockSubtitle.
type MockSubtitleMockRecorder struct {
	mock *MockSubtitle
}

// NewMockSubtitle creates a new mock instance.
func NewMockSubtitle(ctrl *gomock.Controller) *MockSubtitle {
	mock := &MockSubtitle{ctrl: ctrl}
	mock.recorder = &MockSubtitleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubtitle) EXPECT() *MockSubtitleMockRecorder {
	return m.recorder
}

// GetSubtitles mocks base method.
func (m *MockSubtitle) GetSubtitles(ctx context.Context, videoID string) (response.VideoSubtitlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubtitles", ctx, videoID)
	ret0, _ := ret[0].(response.VideoSubtitlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubtitles indicates an expected call of GetSubtitles.
func (mr *MockSubtitleMockRecorder) GetSubtitles(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubtitles", reflect.TypeOf((*MockSubtitle)(nil).GetSubtitles), ctx, videoID)
}

// UploadSubtitles mocks base method.
func (m *MockSubtitle) UploadSubtitles(ctx context.Context, userID, videoID, vttEN, vttVI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSubtitles", ctx, userID, videoID, vttEN, vttVI)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadSubtitles indicates an expected call of UploadSubtitles.
func (mr *MockSubtitleMockRecorder) UploadSubtitles(ctx, userID, videoID, vttEN, vttVI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSubtitles", reflect.TypeOf((*MockSubtitle)(nil).UploadSubtitles), ctx, userID, videoID, vttEN, vttVI)
}

// MockFollow is a mock of Follow interface.
type MockFollow struct {
	ctrl     *gomock.Controller
	recorder *MockFollowMockRecorder
	isgomock struct{}
}

// MockFollowMockRecorder is the mock recorder for MockFollow.
type MockFollowMockRecorder struct {
	mock *MockFollow
}

// NewMockFollow creates a new mock instance.
func NewMockFollow(ctrl *gomock.Controller) *MockFollow {
	mock := &MockFollow{ctrl: ctrl}
	mock.recorder = &MockFollowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollow) EXPECT() *MockFollowMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockFollow) CountFollowers(ctx context.Context, channelID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, channelID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockFollowMockRecorder) CountFollowers(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockFollow)(nil).CountFollowers), ctx, channelID)
}

// IsFollowing mocks base method.
func (m *MockFollow) IsFollowing(ctx context.Context, followerID, channelID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, followerID, channelID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowMockRecorder) IsFollowing(ctx, followerID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollow)(nil).IsFollowing), ctx, followerID, channelID)
}

// ListFollowedChannels mocks base method.
func (m *MockFollow) ListFollowedChannels(ctx context.Context, followerID string, page, limit int) (response.PageResponse[response.ChannelSummary], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowedChannels", ctx, followerID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.ChannelSummary])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowedChannels indicates an expected call of ListFollowedChannels.
func (mr *MockFollowMockRecorder) ListFollowedChannels(ctx, followerID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowedChannels", reflect.TypeOf((*MockFollow)(nil).ListFollowedChannels), ctx, followerID, page, limit)
}

// ToggleFollow mocks base method.
func (m *MockFollow) ToggleFollow(ctx context.Context, followerID, channelID string) (response.FollowToggleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFollow", ctx, followerID, channelID)
	ret0, _ := ret[0].(response.FollowToggleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFollow indicates an expected call of ToggleFollow.
func (mr *MockFollowMockRecorder) ToggleFollow(ctx, followerID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFollow", reflect.TypeOf((*MockFollow)(nil).ToggleFollow), ctx, followerID, channelID)
}

// MockHistory is a mock of History interface.
type MockHistory struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryMockRecorder
	isgomock struct{}
}

// MockHistoryMockRecorder is the mock recorder for MockHistory.
type MockHistoryMockRecorder struct {
	mock *MockHistory
}

// NewMockHistory creates a new mock instance.
func NewMockHistory(ctrl *gomock.Controller) *MockHistory {
	mock := &MockHistory{ctrl: ctrl}
	mock.recorder = &MockHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistory) EXPECT() *MockHistoryMockRecorder {
	return m.recorder
}

// ListHistory mocks base method.
func (m *MockHistory) ListHistory(ctx context.Context, userID string, page, limit int) (response.PageResponse[response.VideoResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistory", ctx, userID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.VideoResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHistory indicates an expected call of ListHistory.
func (mr *MockHistoryMockRecorder) ListHistory(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistory", reflect.TypeOf((*MockHistory)(nil).ListHistory), ctx, userID, page, limit)
}

// RecordWatch mocks base method.
func (m *MockHistory) RecordWatch(ctx context.Context, userID, videoID string, watchSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordWatch", ctx, userID, videoID, watchSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordWatch indicates an expected call of RecordWatch.
func (mr *MockHistoryMockRecorder) RecordWatch(ctx, userID, videoID, watchSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordWatch", reflect.TypeOf((*MockHistory)(nil).RecordWatch), ctx, userID, videoID, watchSeconds)
}

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// BanStream mocks base method.
func (m *MockAdmin) BanStream(ctx context.Context, streamID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanStream", ctx, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanStream indicates an expected call of BanStream.
func (mr *MockAdminMockRecorder) BanStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanStream", reflect.TypeOf((*MockAdmin)(nil).BanStream), ctx, streamID)
}

// BanUser mocks base method.
func (m *MockAdmin) BanUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanUser indicates an expected call of BanUser.
func (mr *MockAdminMockRecorder) BanUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanUser", reflect.TypeOf((*MockAdmin)(nil).BanUser), ctx, userID)
}

// BanVideo mocks base method.
func (m *MockAdmin) BanVideo(ctx context.Context, videoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanVideo", ctx, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanVideo indicates an expected call of BanVideo.
func (mr *MockAdminMockRecorder) BanVideo(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanVideo", reflect.TypeOf((*MockAdmin)(nil).BanVideo), ctx, videoID)
}

// GetDashboard mocks base method.
func (m *MockAdmin) GetDashboard(ctx context.Context) (response.SystemDashboardResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx)
	ret0, _ := ret[0].(response.SystemDashboardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockAdminMockRecorder) GetDashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockAdmin)(nil).GetDashboard), ctx)
}

// GetWorkersStatus mocks base method.
func (m *MockAdmin) GetWorkersStatus(ctx context.Context) ([]response.WorkerStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkersStatus", ctx)
	ret0, _ := ret[0].([]response.WorkerStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkersStatus indicates an expected call of GetWorkersStatus.
func (mr *MockAdminMockRecorder) GetWorkersStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkersStatus", reflect.TypeOf((*MockAdmin)(nil).GetWorkersStatus), ctx)
}

// ListUsers mocks base method.
func (m *MockAdmin) ListUsers(ctx context.Context, page, limit int) (response.PageResponse[response.UserResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.UserResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminMockRecorder) ListUsers(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdmin)(nil).ListUsers), ctx, page, limit)
}

// RecordHeartbeat mocks base method.
func (m *MockAdmin) RecordHeartbeat(ctx context.Context, hb entity.WorkerHeartbeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHeartbeat", ctx, hb)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordHeartbeat indicates an expected call of RecordHeartbeat.
func (mr *MockAdminMockRecorder) RecordHeartbeat(ctx, hb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHeartbeat", reflect.TypeOf((*MockAdmin)(nil).RecordHeartbeat), ctx, hb)
}

// UnbanUser mocks base method.
func (m *MockAdmin) UnbanUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbanUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbanUser indicates an expected call of UnbanUser.
func (mr *MockAdminMockRecorder) UnbanUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbanUser", reflect.TypeOf((*MockAdmin)(nil).UnbanUser), ctx, userID)
}

// MockLike is a mock of Like interface.
type MockLike struct {
	ctrl     *gomock.Controller
	recorder *MockLikeMockRecorder
	isgomock struct{}
}

// MockLikeMockRecorder is the mock recorder for MockLike.
type MockLikeMockRecorder struct {
	mock *MockLike
}

// NewMockLike creates a new mock instance.
func NewMockLike(ctrl *gomock.Controller) *MockLike {
	mock := &MockLike{ctrl: ctrl}
	mock.recorder = &MockLikeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLike) EXPECT() *MockLikeMockRecorder {
	return m.recorder
}

// HeartStream mocks base method.
func (m *MockLike) HeartStream(ctx context.Context, streamID string) (response.HeartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeartStream", ctx, streamID)
	ret0, _ := ret[0].(response.HeartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeartStream indicates an expected call of HeartStream.
func (mr *MockLikeMockRecorder) HeartStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeartStream", reflect.TypeOf((*MockLike)(nil).HeartStream), ctx, streamID)
}

// ToggleLikeVideo mocks base method.
func (m *MockLike) ToggleLikeVideo(ctx context.Context, userID, videoID string) (response.LikeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLikeVideo", ctx, userID, videoID)
	ret0, _ := ret[0].(response.LikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleLikeVideo indicates an expected call of ToggleLikeVideo.
func (mr *MockLikeMockRecorder) ToggleLikeVideo(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLikeVideo", reflect.TypeOf((*MockLike)(nil).ToggleLikeVideo), ctx, userID, videoID)
}

// MockComment is a mock of Comment interface.
type MockComment struct {
	ctrl     *gomock.Controller
	recorder *MockCommentMockRecorder
	isgomock struct{}
}

// MockCommentMockRecorder is the mock recorder for MockComment.
type MockCommentMockRecorder struct {
	mock *MockComment
}

// NewMockComment creates a new mock instance.
func NewMockComment(ctrl *gomock.Controller) *MockComment {
	mock := &MockComment{ctrl: ctrl}
	mock.recorder = &MockCommentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComment) EXPECT() *MockCommentMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockComment) CreateComment(ctx context.Context, videoID, userID, userName, userAvatar string, req request.CreateCommentRequest) (response.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, videoID, userID, userName, userAvatar, req)
	ret0, _ := ret[0].(response.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentMockRecorder) CreateComment(ctx, videoID, userID, userName, userAvatar, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockComment)(nil).CreateComment), ctx, videoID, userID, userName, userAvatar, req)
}

// ListReplies mocks base method.
func (m *MockComment) ListReplies(ctx context.Context, parentID string, page, limit int) (response.PageResponse[response.CommentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, parentID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.CommentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockCommentMockRecorder) ListReplies(ctx, parentID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockComment)(nil).ListReplies), ctx, parentID, page, limit)
}

// ListVideoComments mocks base method.
func (m *MockComment) ListVideoComments(ctx context.Context, videoID string, page, limit int) (response.PageResponse[response.CommentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideoComments", ctx, videoID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.CommentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideoComments indicates an expected call of ListVideoComments.
func (mr *MockCommentMockRecorder) ListVideoComments(ctx, videoID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideoComments", reflect.TypeOf((*MockComment)(nil).ListVideoComments), ctx, videoID, page, limit)
}

// MockRecommendation is a mock of Recommendation interface.
type MockRecommendation struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationMockRecorder
	isgomock struct{}
}

// MockRecommendationMockRecorder is the mock recorder for MockRecommendation.
type MockRecommendationMockRecorder struct {
	mock *MockRecommendation
}

// NewMockRecommendation creates a new mock instance.
func NewMockRecommendation(ctrl *gomock.Controller) *MockRecommendation {
	mock := &MockRecommendation{ctrl: ctrl}
	mock.recorder = &MockRecommendationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendation) EXPECT() *MockRecommendationMockRecorder {
	return m.recorder
}

// GetPersonalizedFeed mocks base method.
func (m *MockRecommendation) GetPersonalizedFeed(ctx context.Context, userID string, page, limit int) (response.PageResponse[response.RecommendedVideoItem], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonalizedFeed", ctx, userID, page, limit)
	ret0, _ := ret[0].(response.PageResponse[response.RecommendedVideoItem])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonalizedFeed indicates an expected call of GetPersonalizedFeed.
func (mr *MockRecommendationMockRecorder) GetPersonalizedFeed(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalizedFeed", reflect.TypeOf((*MockRecommendation)(nil).GetPersonalizedFeed), ctx, userID, page, limit)
}

// MockNotification is a mock of Notification interface.
type MockNotification struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationMockRecorder
	isgomock struct{}
}

// MockNotificationMockRecorder is the mock recorder for MockNotification.
type MockNotificationMockRecorder struct {
	mock *MockNotification
}

// NewMockNotification creates a new mock instance.
func NewMockNotification(ctrl *gomock.Controller) *MockNotification {
	mock := &MockNotification{ctrl: ctrl}
	mock.recorder = &MockNotificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotification) EXPECT() *MockNotificationMockRecorder {
	return m.recorder
}

// ListNotifications mocks base method.
func (m *MockNotification) ListNotifications(ctx context.Context, userID string, page, limit int) (response.NotificationListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, userID, page, limit)
	ret0, _ := ret[0].(response.NotificationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationMockRecorder) ListNotifications(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotification)(nil).ListNotifications), ctx, userID, page, limit)
}

// MarkAsRead mocks base method.
func (m *MockNotification) MarkAsRead(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationMockRecorder) MarkAsRead(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotification)(nil).MarkAsRead), ctx, id, userID)
}

// NotifyFollowers mocks base method.
func (m *MockNotification) NotifyFollowers(ctx context.Context, senderID, senderName, senderAvatar string, notifType entity.NotificationType, title, message, targetURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyFollowers", ctx, senderID, senderName, senderAvatar, notifType, title, message, targetURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyFollowers indicates an expected call of NotifyFollowers.
func (mr *MockNotificationMockRecorder) NotifyFollowers(ctx, senderID, senderName, senderAvatar, notifType, title, message, targetURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFollowers", reflect.TypeOf((*MockNotification)(nil).NotifyFollowers), ctx, senderID, senderName, senderAvatar, notifType, title, message, targetURL)
}

// SubscribeNotifications mocks base method.
func (m *MockNotification) SubscribeNotifications(userID string) (<-chan response.NotificationResponse, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNotifications", userID)
	ret0, _ := ret[0].(<-chan response.NotificationResponse)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeNotifications indicates an expected call of SubscribeNotifications.
func (mr *MockNotificationMockRecorder) SubscribeNotifications(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNotifications", reflect.TypeOf((*MockNotification)(nil).SubscribeNotifications), userID)
}

// MockVocabulary is a mock of Vocabulary interface.
type MockVocabulary struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyMockRecorder
	isgomock struct{}
}

// MockVocabularyMockRecorder is the mock recorder for MockVocabulary.
type MockVocabularyMockRecorder struct {
	mock *MockVocabulary
}

// NewMockVocabulary creates a new mock instance.
func NewMockVocabulary(ctrl *gomock.Controller) *MockVocabulary {
	mock := &MockVocabulary{ctrl: ctrl}
	mock.recorder = &MockVocabularyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabulary) EXPECT() *MockVocabularyMockRecorder {
	return m.recorder
}

// DeleteWord mocks base method.
func (m *MockVocabulary) DeleteWord(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWord", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWord indicates an expected call of DeleteWord.
func (mr *MockVocabularyMockRecorder) DeleteWord(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWord", reflect.TypeOf((*MockVocabulary)(nil).DeleteWord), ctx, id, userID)
}

// ListWords mocks base method.
func (m *MockVocabulary) ListWords(ctx context.Context, userID string) ([]response.VocabularyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWords", ctx, userID)
	ret0, _ := ret[0].([]response.VocabularyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWords indicates an expected call of ListWords.
func (mr *MockVocabularyMockRecorder) ListWords(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWords", reflect.TypeOf((*MockVocabulary)(nil).ListWords), ctx, userID)
}

// LookupWord mocks base method.
func (m *MockVocabulary) LookupWord(ctx context.Context, word string) (response.DictionaryLookupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupWord", ctx, word)
	ret0, _ := ret[0].(response.DictionaryLookupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupWord indicates an expected call of LookupWord.
func (mr *MockVocabularyMockRecorder) LookupWord(ctx, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupWord", reflect.TypeOf((*MockVocabulary)(nil).LookupWord), ctx, word)
}

// SaveWord mocks base method.
func (m *MockVocabulary) SaveWord(ctx context.Context, userID string, req request.SaveWordRequest) (response.VocabularyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWord", ctx, userID, req)
	ret0, _ := ret[0].(response.VocabularyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveWord indicates an expected call of SaveWord.
func (mr *MockVocabularyMockRecorder) SaveWord(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWord", reflect.TypeOf((*MockVocabulary)(nil).SaveWord), ctx, userID, req)
}
